"""SuperMedicine CLI package — re-exports for backward compatibility."""

from cli.helpers import (
    _EXPERIENCE_SCOPE_CHOICES,
    _EXPORT_FORMAT_CHOICES,
    PERMISSION_RISK_NOTICE,
    _as_experience_scope,
    _as_export_format,
    _as_optional_experience_scope,
    _confirm_full_access_interactively,
    _dict_payload,
    _experiment_response,
    _llm_provider_values,
    _load_experiment_session,
    _load_input_json,
    _load_params_file,
    _load_params_json,
    _paper_import_result_to_dict,
    _paper_metadata_options,
    _paper_metadata_to_dict,
    _parse_llm_headers,
    _permission_result,
    _resolve_run_params,
    _save_experiment_session,
    _self_evolution_cli_result,
)
from cli.logging_setup import (
    _configure_cli_logging,
    _configure_stdio_errors,
    _log_json,
    _RedactingFormatter,
)

__all__ = [
    "PERMISSION_RISK_NOTICE",
    "_EXPERIENCE_SCOPE_CHOICES",
    "_EXPORT_FORMAT_CHOICES",
    "_RedactingFormatter",
    "_as_experience_scope",
    "_as_export_format",
    "_as_optional_experience_scope",
    "_configure_cli_logging",
    "_configure_stdio_errors",
    "_confirm_full_access_interactively",
    "_dict_payload",
    "_experiment_response",
    "_llm_provider_values",
    "_load_experiment_session",
    "_load_input_json",
    "_load_params_file",
    "_load_params_json",
    "_log_json",
    "_paper_import_result_to_dict",
    "_paper_metadata_options",
    "_paper_metadata_to_dict",
    "_parse_llm_headers",
    "_permission_result",
    "_resolve_run_params",
    "_save_experiment_session",
    "_self_evolution_cli_result",
]
